---
title: "Making choices inside R functions"
author: "Marcos Padilla-Ruiz"
date: "2022-11-11"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction To Conditional Statements
```{r, eval=FALSE}
weight > 50
species == "DM"

"aang" == "aang"
"aang" == "kora"
"aang" != "kora"
10 < 5
10 >= 5
is.na("toph")

"zuko" %in% c("aang", "toph", "katara", "zuko")

5 > 2 & 6 >= 10
5 > 2 | 6 >= 10

c(1, 1, 2, 3, 1) == 1

site = c('a', 'b', 'c', 'd')
state = c('FL', 'FL', 'GA', 'AL')
state == 'FL'

site[state == 'FL']
site[c(TRUE, TRUE, FALSE, FALSE)]
```


## Introduction To if Statements In R
```{r}
# if (the conditional statement is TRUE) {
 # do something
#}

x = 6
if (x > 5) {
  x = x^2
}

veg_type = "tree"
volume = 16.08
if (veg_type == "tree") {
  mass = 2.65 * volume^0.9
} else if (veg_type == "grass") {
  mass = 0.65 * volume^1.2
} else {
  mass = NA
}
```


## Introduction To else if And else Statements in R
```{r}
veg_type = "grass"
volume = 16.08
if (veg_type == "tree") {
  mass = 2.65 * volume^0.9
} else if (veg_type == "grass") {
  mass = 0.65 * volume^1.2
} else {
  mass = NA
}
```


## Using if/else if/else Statements Inside of Functions in R
```{r}
veg_type = "shrub"
volume = 16.08
if (veg_type == "tree") {
  mass = 2.65 * volume^0.9
} else if (veg_type == "grass") {
  mass = 0.65 * volume^1.2
} else {
  mass = NA
}

est_mass = function(volume, veg_type) {
  if (veg_type == "tree") {
    mass = 2.65 * volume^0.9
  } else if (veg_type == "grass") {
    mass = 0.65 * volume^1.2
  } else {
    mass = NA
  }
  return(mass)
}
est_mass(1.6, "tree")
est_mass(1.6, "grass")
est_mass(1.6, "shrub")
```


## Introduction To Nested if Statements in R
```{r}
est_mass = function(volume, veg_type, age) {
  if (veg_type == "tree") {
    if (age < 5) {
      mass = 1.6 * volume^0.9
    } else {
      mass = 2.65 * volume^0.9
    }  
  } else if (veg_type == "grass") {
    mass = 0.65 * volume^1.2
  } else {
    mass = NA
  }
  return(mass)
}
est_mass(1.6, "tree", 4)
est_mass(1.6, "tree", 6)
est_mass(1.6, "grass")
est_mass(1.6, "shrub")
```








