---
title: "Loops"
author: "Marcos Padilla-Ruiz"
date: "2022-11-17"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
sum(1, 2, 3, 4, 5)
sum(19, 11, 04, 27)
sum(37, 456, 378)
```

1.
```{r, eval=FALSE}
numbers <- 1:5
numbers <- seq(1, 5, 1)
read.csv(file = "../raw_data.species.csv")
mass <- a * length ^ b
for (item in numbers) {
  print(x = item)
  print("Hello")
}
for (item in 1:5) {
  print(x = item)
  print("New")
}
for (dumpling in 1:5) {
  print(x = dumpling)
  print("New")
}
```

2.
```{r}
mass_lbs <- c(2.2, 3.5, 9.6, 1.2)
for(items in mass_lbs){
   print(items)
  mass_kg = 2.2 * items
  print(mass_kg)
}

our_names <- c("Azul", "Jai", "Marcos", "Luna")
for(name in our_names) {
  print(name)
}
```

3.
```{r}
birds <-  c('robin', 'woodpecker', 'blue jay', 'sparrow')
for (i in 1:length(birds)){
  print(birds[i])
}
```


4.
```{r}
radius <- c(1.3, 2.1, 3.5)

areas <- vector(mode = "numeric", length = length(radius))
for (i in 1:length(areas)){
  areas[i] <- pi * radius[i] ^ 2
}
areas

```

5.
```{r}
lengths = c(1.1, 2.2, 1.6)
widths = c(3.5, 2.4, 2.8)
areas <- vector(length = 3)
for (i in 1:length(areas)) {
  areas[i] <- lengths[i] * widths[i]
}
areas
```


6.
```{r}
dino_lengths <- read.csv(file = "../raw_data/dinosaur_lengths.csv")
species <- read.csv(file = "../raw_data/species.csv")
```


```{r}
library(dplyr)
mass_from_length <- function(length, species) {
  if (species == "Stegosauria") {
    a <- 10.95
    b <- 2.64
  } else if (species == "Theropoda") {
  a <- 0.73 
  b <- 3.63
  } else if (species == "Sauropoda") {
  a <- 214.44 
  b <- 1.46
  } else {
  a <- 25.37
  b <- 2.49
}

mass <- a*length^b
return(mass)
}

```

```{r, eval=FALSE}
dino_lengths %>% mutate(dino_mass = mass_from_length(lengths, species))
lengths <- dino_lengths$lengths
species <- dino_lengths$species
masses <- vector(length = length(lengths))
for (i in 1:length(species)) {
  masses[i] <- length[i] * mass_from_length[i]
}
masses

```
