---
title: "vectors and data frames"
author: "Marcos Padilla-Ruiz"
date: "2022-10-20"
output: pdf_document
---



# the relationhsip between vectors and dataframes

## how to cerate vectors

```{r}
a_number <- 100 
length(a_number)
c(1,2,3)
c(FALSE,TRUE, TRUE)
c("Luna","Jai","Azul","Marcos")
1:4
0.5:5
c(1,6,7,100, -1)
1:100
long_vector <- 1:546378
length(long_vector)
tail(long_vector)
seq(1,100,0.3)# 1- 100 in increments of 0.3
seq(-100,5,2)
100:20
-100:5 # start. end 
rep(1:5, 3) # 1- 5 REPEATERD 3 times 
rep("luna",100)
rep(c(TRUE, FALSE, TRUE),7)
letters
LETTERS
```


## joining vectors to create data frames

```{r}
year_data <- data.frame(names = c("Azul", "Jai", "Marcos"), 
                        year = c(4, 3, 4),
                        college = "UC Merced")

year_data


```


```{r}
length <- c(2.2, 2.1, 2.7, 3.0, 3.1, 2.5, 1.9, 1.1, 3.5, 2.9)
width <- c(1.3, 2.2, 1.5, 4.5, 3.1, NA, 1.8, 0.5, 2.0, 2.7)
height <- c(9.6, 7.6, 2.2, 1.5, 4.0, 3.0, 4.5, 2.3, 7.5, 3.2)

taxus_baccata <- data.frame(length, width, height, genus = "Taxus", species = "Baccata")

taxus_baccata
```


## extracting values from vectors and data frames

```{r}
surveys <- read.csv(file = "../raw_data/surveys.csv")

# extracts one column at a time
surveys$year

# to extract rows or multiple columns use square brackets
surveys[1, 2]
surveys[1:5,]
surveys[10:5, c("month", "year")]

# keeps data frame structure
surveys["month"]

# way to access values of a column as a vector
surveys[["month"]]


```



exercise 2

```{r}
surveys_weight <- surveys$weight

surveys_month <- surveys[,"month"]

surveys$hindfoot_length %>% 
  mean(na.rm = TRUE) -> surveys_hindfoot



```


### extract values from vectors

```{r}
letters[1:5]
letters[c(17, 12, 9, 3)]
letters[5:1]
letters[-1]
letters[-c(1,6,7,8)]

# "-" can be used to get rid of columns
colnames(surveys)
surveys[,-(1:4)]
```








